{{- if .Values.pgVote.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.pgVote.clusterName }}
  namespace: {{ .Values.pgVote.namespace }}
  annotations:
    eks.amazonaws.com/role-arn: {{ include "cnpg-clusters.iam-role" . | quote }}
automountServiceAccountToken: true
{{- end }}
{{- if .Values.pgKeycloak.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.pgKeycloak.clusterName }}
  namespace: {{ .Values.pgKeycloak.namespace }}
  annotations:
    eks.amazonaws.com/role-arn: {{ include "cnpg-clusters.iam-role" . | quote }}
automountServiceAccountToken: true
{{- end }}
