apiVersion: v1
kind: Service
metadata:
  name: {{ include "vote.fullname" . }}
  annotations:
    alb.ingress.kubernetes.io/target-type: ip
  labels:
    {{- include "vote.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.name }}
  selector:
    app.kubernetes.io/name: {{ include "vote.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
