{{- if .Values.vaultDynamicSecret.enabled }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: {{ .Values.vaultDynamicSecret.destination.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.vaultDynamicSecret.destination.name }}
    app.kubernetes.io/managed-by: vault-secrets-operator
spec:
  mount: {{ .Values.vaultDynamicSecret.engineMount }}
  role: {{ .Values.vaultDynamicSecret.role }}
  {{- if .Values.vaultDynamicSecret.path }}
  path: {{ .Values.vaultDynamicSecret.path }}
  {{- end }}
  vaultAuthRef: default
  refreshPeriod: {{ .Values.vaultDynamicSecret.refreshPeriod }}
  revocationDuration: {{ .Values.vaultDynamicSecret.revocationDuration }}
  destination:
    name: {{ .Values.vaultDynamicSecret.destination.name }}
    create: {{ .Values.vaultDynamicSecret.destination.create }}
    labels:
      {{- toYaml .Values.vaultDynamicSecret.destination.labels | nindent 6 }}
{{- end }}
