prometheus:
  prometheusSpec:
    storageSpec:
      disableMountSubPath: true
grafana:
  persistence:
    enabled: false
alertmanager:
  alertmanagerSpec:
    storageSpec:
      disableMountSubPath: true
