replicaCount: 1

image:
  repository: 765776786215.dkr.ecr.eu-central-1.amazonaws.com/my-app/worker
  tag: 1.0.0
  pullPolicy: IfNotPresent

postgresql:
  host: postgresql
  port: 5432
  database: db
  user: vote_user
  existingSecret: postgresql
  secretPasswordKey: password

redis:
  host: redis-master
  port: 6379
