replicaCount: 1

global:
  awsAccountId: "AWS_ACCOUNT_ID"
  awsRegion: "eu-central-1"

image:
  repository: my-app/worker
  digest: sha256:11ccdd9b86afe8d98f48481573def6aa21bf2fbedc117c7106b2fd6d9d5e775a
  tag: ""
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: ""
  annotations: {}

pdb:
  create: true
  minAvailable: 1

scaledObject:
  create: true
  minReplicas: 1
  maxReplicas: 10
  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: "70"
    - type: memory
      metricType: Utilization
      metadata:
        value: "80"
    - type: rabbitmq
      metadata:
        queueName: votes
        host: amqp://voting-app:CHANGEME_rabbitmq@rabbitmq.voting-app:5672
        protocol: amqp
        mode: QueueLength
        value: "10"

networkPolicy:
  create: true

postgresql:
  host: pg-vote-rw
  port: 5432
  database: db
  # ─── Dynamic credentials from VSO (VaultDatabaseSecret) ─────
  existingSecret: pg-vote-dynamic
  secretUsernameKey: username
  secretPasswordKey: password

rabbitmq:
  host: rabbitmq
  port: 5672
  user: voting-app
  existingSecret: rabbitmq-default-user
  secretUsernameKey: username
  secretPasswordKey: password

probes:
  readinessPath: /
  livenessPath: /
  readinessDelay: 5
  livenessDelay: 15
  periodSeconds: 10
  timeoutSeconds: 3
  failureThreshold: 3

resources:
  requests:
    memory: 256Mi
    cpu: 200m
  limits:
    memory: 512Mi
    cpu: 1000m
