replicaCount: 2
global:
  awsAccountId: "AWS_ACCOUNT_ID"
  awsRegion: "eu-central-1"
image:
  repository: my-app/vote
  digest: sha256:0e0118f594e5d348b7296cb268bdf9a4e3c72277e8bc333a0b6b50ccec297b48
  tag: ""
  pullPolicy: IfNotPresent

serviceAccount:
  create: false
  name: ""
  annotations: {}

postgresql:
  host: postgresql
  port: 5432
  database: db
  user: vote_user
  existingSecret: postgresql
  secretPasswordKey: password

redis:
  host: redis-master
  port: 6379

service:
  targetPort: 80

probes:
  readinessPath: /
  livenessPath: /
  readinessDelay: 5
  livenessDelay: 15
  periodSeconds: 10
  timeoutSeconds: 3
  failureThreshold: 3

canary:
  steps:
    - setWeight: 20
    - pause: {duration: 30}
    - setWeight: 50
    - pause: {duration: 30}
    - setWeight: 80
    - pause: {duration: 15}
