replicaCount: 4
global:
  awsAccountId: "AWS_ACCOUNT_ID"
  awsRegion: "eu-central-1"
image:
  repository: my-app/vote
  tag: stable
  pullPolicy: IfNotPresent

postgresql:
  host: postgresql
  port: 5432
  database: db
  user: vote_user
  existingSecret: postgresql
  secretPasswordKey: password

redis:
  host: redis-master
  port: 6379

canary:
  steps:
    - setWeight: 20
    - pause: {duration: 30}
    - setWeight: 50
    - pause: {duration: 30}
    - setWeight: 80
    - pause: {duration: 15}
