replicaCount: 4
image:
  repository: 657954628960.dkr.ecr.eu-central-1.amazonaws.com/my-app/vote
  tag: latest
  pullPolicy: IfNotPresent

postgresql:
  host: postgresql
  port: 5432
  database: db
  user: vote_user
  existingSecret: postgresql
  secretPasswordKey: password

redis:
  host: redis-master
  port: 6379

canary:
  steps:
    - setWeight: 20
    - pause: {duration: 30}
    - setWeight: 50
    - pause: {duration: 30}
    - setWeight: 80
    - pause: {duration: 15}
