apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: worker
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mochthebest-byte/my-devops-project.git
    targetRevision: HEAD
    path: voting-app-worker/charts/worker
  destination:
    server: https://kubernetes.default.svc
    namespace: voting-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
