---
# ─────────────────────────────────────────────────────
# ExternalSecret — Grafana OIDC client secret
# Джерело: AWS Secrets Manager (/my-app/grafana-oidc)
# Створює k8s Secret: grafana-oidc-secret
# ─────────────────────────────────────────────────────
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-oidc
  namespace: monitoring
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: grafana-oidc-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: client-secret
      remoteRef:
        key: /my-app/grafana-oidc
        property: client-secret
