---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgresql
  namespace: voting-app
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: postgresql
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: password
      remoteRef:
        key: /my-app/postgresql
        property: password
    - secretKey: postgres-password
      remoteRef:
        key: /my-app/postgresql
        property: postgres-password
