image: docker.io/library/redis@sha256:2838d5524559494f6f1cd66e97e76b200d64a633a8614200620755ed395daf32
replicaCount: 1
service:
  port: 6379
  targetPort: 6379
resources:
  requests:
    memory: 128Mi
    cpu: 50m
  limits:
    memory: 256Mi
    cpu: 200m
persistence:
  storageClass: gp3
  size: 4Gi
