apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-postgresql
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: oci://registry-1.docker.io/bitnamicharts
    targetRevision: 18.7.x
    chart: postgresql
    helm:
      values: |
        image:
          tag: latest
        auth:
          database: keycloak
          username: keycloak
          existingSecret: keycloak-db
        primary:
          service:
            type: ClusterIP
          persistence:
            storageClass: gp3
            size: 5Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
