apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-tempo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/mochthebest-byte/my-devops-project.git
    targetRevision: HEAD
    path: charts/loki-tempo
  destination:
    server: https://kubernetes.default.svc
    namespace: loki
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
