apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/refresh: "hard"
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 16.x
    chart: postgresql
    helm:
      values: |
        image:
          tag: latest@sha256:256bf40a7343862b9a66d1d27cd34599e80dad99284fc5450b24cb02e26ff34e
        auth:
          database: db
          username: vote_user
          existingSecret: postgresql   # створюється ESO з AWS Secrets Manager /my-app/postgresql
        primary:
          service:
            type: ClusterIP
          persistence:
            storageClass: gp3
            size: 8Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: voting-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
