apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 21.x
    chart: redis
    helm:
      values: |
        image:
          tag: ""
          digest: sha256:f7c13b6242eca1256dc5b5ee9f5a2b6279636293b2955d9f4336def3238e85ee
        architecture: standalone
        auth:
          enabled: false
        master:
          persistence:
            storageClass: gp3
            size: 4Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: voting-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
