apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: result
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://github.com/mochthebest-byte/my-devops-project.git
    targetRevision: HEAD
    path: voting-app-result/charts/result
    helm:
      values: |
        global:
          awsAccountId: {{ .Values.global.awsAccountId | quote }}
          awsRegion: {{ .Values.global.awsRegion | quote }}
  destination:
    server: https://kubernetes.default.svc
    namespace: voting-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
