apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://strimzi.io/charts/
    chart: strimzi-kafka-operator
    targetRevision: 1.1.0
    helm:
      values: |
        replicas: 1
        watchNamespaces:
          - default
        createGlobalRoles: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
