apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-vote-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/mochthebest-byte/my-devops-project.git
    targetRevision: HEAD
    path: charts/vso-config
    helm:
      values: |
        global:
          vaultAddress: http://vault.vault.svc.cluster.local:8200
        vaultConnection:
          enabled: true
        vaultAuth:
          enabled: true
          role: vault-secrets-operator
          serviceAccount: vault-secrets-operator-controller
        vaultDynamicSecret:
          enabled: true
          engineMount: database
          role: voting-app-dynamic
          destination:
            name: pg-vote-dynamic
            create: true
            labels:
              app.kubernetes.io/managed-by: vault-secrets-operator
              app.kubernetes.io/component: dynamic-secret
          refreshPeriod: 30s
          revocationDuration: 60s
        vaultPKI:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: voting-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
