apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-secrets-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"     # Same wave as Vault
spec:
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 1.4.x
    chart: vault-secrets-operator
    helm:
      values: |
        defaultVaultConnection:
          enabled: false
        defaultAuthMethod:
          enabled: false
        controller:
          manager:
            resources:
              requests:
                memory: 64Mi
                cpu: 50m
              limits:
                memory: 256Mi
                cpu: 200m
  destination:
    server: https://kubernetes.default.svc
    namespace: vault-secrets-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
