apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-init
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/mochthebest-byte/my-devops-project.git
    targetRevision: HEAD
    path: charts/vault-init
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
