apiVersion: v1
kind: Secret
metadata:
  name: voting-app-tls
  namespace: voting-app
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-central-1:657954628960:certificate/22036369-7242-4539-8cf7-dadec0e93164
type: Opaque
data: {}
