replicaCount: 2

image:
  repository: 657954628960.dkr.ecr.eu-central-1.amazonaws.com/my-app/vote
  # pinned by digest — immutable reference, never changes
  tag: latest@sha256:d461cf7997c95860b4008677a2a40e62697067f8a9f2ee71e7f114ef371b3fc5
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000
  targetPort: 80
  protocol: TCP
  name: http

postgresql:
  host: postgresql
  port: 5432
  database: db
  user: vote_user
  existingSecret: postgresql
  secretPasswordKey: password

resources:
  requests:
    memory: 128Mi
    cpu: 100m
  limits:
    memory: 256Mi
    cpu: 500m

redis:
  host: redis-master
  port: 6379
