replicaCount: 2

image:
  repository: 657954628960.dkr.ecr.eu-central-1.amazonaws.com/my-app/vote
  # pinned by digest — immutable reference, never changes
  tag: latest@sha256:da47fdb93d92a2872f0b970114b51094491790ba2f6c065849dc6d299dc21069
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000
  targetPort: 80
  protocol: TCP
  name: http

postgresql:
  host: postgresql
  port: 5432
  database: db
  user: vote_user
  existingSecret: postgresql
  secretPasswordKey: password

resources:
  requests:
    memory: 128Mi
    cpu: 100m
  limits:
    memory: 256Mi
    cpu: 500m

redis:
  host: redis-master
  port: 6379
