apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: rabbitmq
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: {{ .Values.image }}
          ports:
            - name: amqp
              containerPort: 5672
            - name: http
              containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "voting-app"
            - name: RABBITMQ_DEFAULT_PASS
              value: "CHANGEME_rabbitmq"
          resources: {{ toYaml .Values.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: http
      port: 15672
      targetPort: 15672
